### ISSUE TITLE
这命令行简直一言难尽啊

### ISSUE THREAD

**Issue by bd-dxg** [maxiaoqu/nrm#2]
首先是 安装包的包名 叫invm  

nvm 是管理node 版本的一个包
而nrm 是管理node 下载镜像的一个包

现在新包名字 invm 顾名思义 应该是个管理node版本切换的包，实际上干的是切换镜像的事情 简直成了四不像

更不用说提供的命令 还是
```bash
$ nvm ls
$ nvm list
$ nvm ping
$ nvm test
$ nvm now
```
你让安装了nvm的人怎么想？
nvm ls  到底是列出node 版本列表呢 还是node 镜像源列表？

然后你们是提供了另一种命令 inrm 对 挺好的  但这个和包名有什么关系了 安装包用 invm 使用命令 inrm 不觉得匪夷所思吗？

只是吐槽，但对你们做了这个新的包，还是要道一声 大佬辛苦了

**Comment by maxiaoqu** [comment]
谢谢提醒，包的名字一值叫inrm，命令是nrm或者inrm，只是在编辑文档的过程中写错了，感谢纠正！
